//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfernoMonkeyGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        public int characterID { get; set; }
        public string name { get; set; }
        public Nullable<int> strength { get; set; }
        public Nullable<int> health { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> losses { get; set; }
        public string quote { get; set; }
        public Nullable<int> weapon { get; set; }
    }
}
