//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfernoMonkeyGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int imageId { get; set; }
        public int loginId { get; set; }
        public byte[] image1 { get; set; }
    }
}
